### ISSUE TITLE
orphaned jobs

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#389]
pluto ver 0.9.4

If a pluto server dies while processing a job the run record will remain in "running" status and become orphaned.  This leads to the following issues:

1) In the "Edit Validation UI" it will show the processing spinning wheel even though no server is processing it.  This is confusing to the user.  In order to manually trigger the job the user must edit the validation instead of clicking "Upload" directly from the "Edit Validation UI" screen.
2) The runs history becomes confusing due to the record remaining in a persisted "running" state.

**Comment by lcorrigall** [comment]
There are some handling for this (if another job is kicked off externally for the same file, it will get marked "failed" for unknown reasons), but agreed we need a better way to handle this.

**Comment by lcorrigall** [comment]
From #425:
Pluto ver 0.9.6

The plugins (exporter/importer) purposefully do not catch their exceptions because the pluto_server itself catches them and reports errors to the user. However in this event the user will only see the following on the UI: "Error | ProcessFileRouter | Run stopped without cleaning up. Server has marked this as finished.". However it'll be more useful to see the actual exception trace on the UI as well. Otherwise users will need to redirect to kibana and/or the docker logs to determine what the actual error is.

**Comment by lcorrigall** [comment]
To Address:
If the validator process crashes, the error log will be added to the error messages reported to the server

If we hit the timeout on a server that didn't start the job, indicate that the likely reason was an unexpected server error and to talk to the administrators

At server startup, and on a regular interval, check to see if there are any hung jobs and terminate them. Use runMaximumDuration + 1 minute + 0-5 random minutes

**Comment by lcorrigall** [comment]
Adding the hung job checking to issue #479
