### ISSUE TITLE
Update to CircleCI 2.0 before August deadline.

### ISSUE THREAD

**Issue by pandersen-uncharted** [unchartedsoftware/PLUTO#526]

**Comment by bb-acarrera** [comment]
Per https://circleci.com/docs/2.0/building-docker-images/#mounting-folders docker volume mounts are no longer valid.  Therefore all builds will fail due to https://github.com/unchartedsoftware/PLUTO/blob/48035b455c3e7b7fe2f247b4f46fda8468dc1f86/build/bin/runUnitTestsCI.sh#L12.  This will need to be changed to copy the contents into the docker container
