### ISSUE TITLE
Post Process Task - Carto UI

### ISSUE THREAD

**Issue by bb-acarrera** [unchartedsoftware/PLUTO#564]
In CartoTableUI.js the javascript makes a http call to populate the values in the dropdown for dataset and column.  However when the user types into the dropdown it doesn't properly filter and yields no result.

**Comment by pandersen-uncharted** [comment]
When getting the list to display from a remote location the code is returning a Promise which resolves to the list. The power-select component doesn't appear to like this and outputs the following error:

`Error: Assertion Failed: {{power-select}} If you want the default filtering to work on options that are not plain strings, you need to provide 'searchField'`

I need to read up on the power-select component to see how to get around this, since a Promise doesn't have fields to search.
